// <auto-generated />
using System;
using LoginRegistration.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoginRegistration.Migrations
{
    [DbContext(typeof(DemoContext))]
    partial class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LoginRegistration.Models.EvilGroup", b =>
                {
                    b.Property<int>("EvilGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("EvilGroupId");

                    b.ToTable("EvilGroups");
                });

            modelBuilder.Entity("LoginRegistration.Models.Plan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<decimal>("Cost");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<TimeSpan>("Duration");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("VillainId");

                    b.HasKey("PlanId");

                    b.HasIndex("VillainId");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("LoginRegistration.Models.Villain", b =>
                {
                    b.Property<int>("VillainId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("VillainId");

                    b.ToTable("Villains");
                });

            modelBuilder.Entity("LoginRegistration.Models.VillainEvilGroup", b =>
                {
                    b.Property<int>("VillainEvilGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("EvilGroupId");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("VillainId");

                    b.HasKey("VillainEvilGroupId");

                    b.HasIndex("EvilGroupId");

                    b.HasIndex("VillainId");

                    b.ToTable("VillainEvilGroups");
                });

            modelBuilder.Entity("LoginRegistration.Models.Plan", b =>
                {
                    b.HasOne("LoginRegistration.Models.Villain", "Villain")
                        .WithMany("Plans")
                        .HasForeignKey("VillainId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LoginRegistration.Models.VillainEvilGroup", b =>
                {
                    b.HasOne("LoginRegistration.Models.EvilGroup", "EvilGroup")
                        .WithMany("VillainEvilGroups")
                        .HasForeignKey("EvilGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LoginRegistration.Models.Villain", "Villain")
                        .WithMany("VillainEvilGroups")
                        .HasForeignKey("VillainId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
